import { useCallback, useEffect, useState } from "react";
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import "./dashboard.css";

const API = "/api";
const money = (n = 0) => `₹${new Intl.NumberFormat("en-IN", { maximumFractionDigits: 0 }).format(n)}`;
const precise = (n = 0) => `₹${Number(n).toFixed(2)}`;

function useApi(path, delay) {
  const [data, setData] = useState(null); const [error, setError] = useState(false);
  const load = useCallback(async () => { try { const r = await fetch(`${API}${path}`); if (!r.ok) throw Error(); setData(await r.json()); setError(false); } catch { setError(true); } }, [path]);
  useEffect(() => { load(); const id = setInterval(load, delay); return () => clearInterval(id); }, [load, delay]);
  return { data, error };
}
function Panel({ title, children, note }) { return <section className="panel"><header><h2>{title}</h2>{note && <small>{note}</small>}</header>{children}</section>; }
function Empty({ children }) { return <div className="empty">{children}</div>; }
function Metric({ label, value, tone = "blue" }) { return <article className="metric"><small>{label}</small><strong className={tone}>{value}</strong></article>; }
function Status({ label, value, good }) { return <div className="status"><span>{label}</span><b className={good ? "good" : "warn"}><i />{value}</b></div>; }

export default function App() {
  const portfolio = useApi("/portfolio", 5000), trades = useApi("/trades", 10000), signals = useApi("/signals", 10000), equity = useApi("/equity-curve", 30000), pnl = useApi("/pnl/daily", 30000), agents = useApi("/agents/status", 15000), health = useApi("/health", 5000);
  const [live, setLive] = useState(null), [busy, setBusy] = useState(false), [connected, setConnected] = useState(false);
  useEffect(() => { const e = new EventSource(`${API}/stream`); e.onopen = () => setConnected(true); e.onerror = () => setConnected(false); e.onmessage = ({ data }) => { try { const event = JSON.parse(data); if (event.type === "system_status") setLive(event.data); } catch {} }; return () => e.close(); }, []);
  const state = live || health.data, p = portfolio.data, daily = p?.daily_pnl || 0, failed = [portfolio,trades,signals,equity,pnl,agents,health].some(x => x.error);
  const control = async action => { setBusy(true); try { const r = await fetch(`${API}/control`, {method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action})}); const body = await r.json(); setLive(body.system); } finally { setBusy(false); } };
  return <main className="app">
    <header className="top"><div><small className="eyebrow">AUTONOMOUS EXECUTION CONSOLE</small><h1>India AI Trader</h1></div><div className="badges"><span className={connected ? "connected" : "disconnected"}><i />{connected ? "LIVE FEED" : "POLLING"}</span><span className={state?.paper_trading ? "paper" : "live"}>{state?.mode || "CHECKING"}</span></div></header>
    {failed && <div className="notice">Some dashboard data is unavailable. Requests will retry automatically.</div>}
    {state?.dead_mans_switch?.halted && <div className="notice danger">Circuit breaker active: {state.dead_mans_switch.halt_reason}</div>}
    <section className="metrics"><Metric label="Portfolio value" value={money(p?.total_value)}/><Metric label="Today’s P&L" value={`${daily >= 0 ? "+" : ""}${money(daily)}`} tone={daily >= 0 ? "green" : "red"}/><Metric label="Available capital" value={money(p?.available_capital)} tone="purple"/><Metric label="Open positions" value={p?.position_count || 0} tone="white"/></section>
    <section className="grid primary"><Panel title="Equity curve" note="Daily snapshots">{equity.data?.length ? <ResponsiveContainer width="100%" height={250}><AreaChart data={equity.data}><defs><linearGradient id="g" x1="0" x2="0" y1="0" y2="1"><stop stopColor="#7181ff" stopOpacity=".5"/><stop offset="1" stopColor="#7181ff" stopOpacity="0"/></linearGradient></defs><CartesianGrid vertical={false}/><XAxis dataKey="date"/><YAxis/><Tooltip formatter={money}/><Area dataKey="value" type="monotone" stroke="#8e9aff" fill="url(#g)"/></AreaChart></ResponsiveContainer> : <Empty>Curve appears after the first daily snapshot.</Empty>}</Panel><Panel title="System controls"><div className="statuses"><Status label="Scheduler" value={state?.scheduler_running ? "Running" : "Not started"} good={state?.scheduler_running}/><Status label="New entries" value={state?.trading_paused ? "Paused" : "Enabled"} good={!state?.trading_paused}/><Status label="Broker" value={state?.broker_authenticated ? "Authenticated" : state?.broker_configured ? "Configured" : "Paper fallback"} good={Boolean(state?.broker_authenticated || !state?.broker_configured)}/><Status label="Circuit breaker" value={state?.dead_mans_switch?.halted ? "HALTED" : "Clear"} good={!state?.dead_mans_switch?.halted}/></div><div className="buttons"><button disabled={busy || state?.trading_paused} onClick={() => control("pause")}>Pause new entries</button><button className="resume" disabled={busy || !state?.trading_paused} onClick={() => control("resume")}>Resume after review</button></div><p className="hint">Stops and time exits continue while entries are paused. Live mode cannot be changed here.</p></Panel></section>
    <section className="grid thirds"><Panel title="Daily P&L">{pnl.data?.length ? <ResponsiveContainer width="100%" height={180}><BarChart data={pnl.data}><CartesianGrid vertical={false}/><XAxis dataKey="date"/><YAxis/><Tooltip formatter={precise}/><Bar dataKey="pnl">{pnl.data.map((x,i)=><Cell key={i} fill={x.pnl >= 0 ? "#27d5a2" : "#ff6e83"}/>)}</Bar></BarChart></ResponsiveContainer>:<Empty>Waiting for a market-close snapshot.</Empty>}</Panel><Panel title="Pipeline readiness"><div className="agents">{(agents.data || []).map(a=><span className={a.status} key={a.name}><i />{a.name.replace("Agent","")}</span>)}</div></Panel><Panel title="Latest execution">{trades.data?.[0] ? <div className="latest"><b className={trades.data[0].action === "BUY" ? "buy" : "sell"}>{trades.data[0].action}</b><strong>{trades.data[0].symbol}</strong><p>{trades.data[0].quantity} units at {precise(trades.data[0].price)}</p><small>{trades.data[0].status} · {trades.data[0].strategy || "Pipeline"}</small></div>:<Empty>No execution yet.</Empty>}</Panel></section>
    <section className="grid tables"><Panel title="Open positions"><Positions rows={p?.positions || []}/></Panel><Panel title="Recent decisions"><Signals rows={signals.data || []}/></Panel></section><Panel title="Execution ledger"><Trades rows={trades.data || []}/></Panel>
  </main>;
}
function Positions({rows}) { return rows.length ? <Table heads={["Symbol","Qty","Average","LTP","P&L"]}>{rows.map(x=><tr key={x.symbol}><td><b>{x.symbol}</b><small>{x.product}</small></td><td>{x.quantity}</td><td>{precise(x.avg_price)}</td><td>{precise(x.ltp)}</td><td className={x.pnl >= 0 ? "green" : "red"}>{x.pnl >= 0 ? "+" : ""}{precise(x.pnl)}</td></tr>)}</Table>:<Empty>No open positions.</Empty>; }
function Signals({rows}) { return rows.length ? <div className="signal-list">{rows.slice(0,8).map(x=><article className="signal" key={x.id}><b className={x.signal.includes("BUY")?"buy":x.signal.includes("SELL")?"sell":"hold"}>{x.signal}</b><div><strong>{x.symbol}</strong><p>{x.reasoning || "No rationale recorded"}</p></div><small>{x.confidence ?? "—"}%</small></article>)}</div>:<Empty>No decisions recorded.</Empty>; }
function Trades({rows}) { return rows.length ? <Table heads={["Time","Symbol","Side","Price","Qty","Strategy","Status","P&L"]}>{rows.slice(0,20).map(x=><tr key={x.id}><td>{x.created_at ? new Date(x.created_at).toLocaleString("en-IN",{hour:"2-digit",minute:"2-digit",day:"2-digit",month:"short"}):"—"}</td><td><b>{x.symbol}</b></td><td><b className={x.action === "BUY" ? "buy" : "sell"}>{x.action}</b></td><td>{precise(x.price)}</td><td>{x.quantity}</td><td>{x.strategy || "Pipeline"}</td><td><small className="pill">{x.status}</small></td><td className={(x.pnl || 0)>=0?"green":"red"}>{x.pnl == null ? "—" : precise(x.pnl)}</td></tr>)}</Table>:<Empty>No executions recorded.</Empty>; }
function Table({heads,children}) { return <div className="scroll"><table><thead><tr>{heads.map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{children}</tbody></table></div>; }
